//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status_name")]
pub enum StatusName {
    #[sea_orm(string_value = "error")]
    Error,
    #[sea_orm(string_value = "in-progress")]
    InProgress,
    #[sea_orm(string_value = "success")]
    Success,
}
